---
- name: Wait for K3s API
  shell: |
    kubectl get nodes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: result
  retries: 30
  delay: 5
  until: result.rc == 0
  changed_when: false

- name: Ensure kubeconfig is readable for vagrant
  shell: |
    cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
    chown -R vagrant:vagrant /home/vagrant/.kube
    chmod 600 /home/vagrant/.kube/config
  args:
    creates: /home/vagrant/.kube/config
