expose:
  type: clusterIP
  tls:
    enabled: false
  clusterIP:
    name: harbor
    ports:
      httpPort: 80

externalURL: http://harbor.192-168-100-240.nip.io

existingSecretAdminPassword: harbor-admin-password
existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
existingSecretSecretKey: harbor-core-secret-key

persistence:
  enabled: true
  resourcePolicy: keep
  persistentVolumeClaim:
    registry:
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 10Gi
    jobservice:
      jobLog:
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 1Gi
    database:
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 2Gi
    redis:
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 1Gi
    trivy:
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 2Gi
  imageChartStorage:
    type: filesystem

updateStrategy:
  type: Recreate

trivy:
  enabled: true
  ignoreUnfixed: false
  severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

logLevel: info
