apiVersion: v1
kind: Secret
metadata:
  name: jenkins-agent-manager-token
  namespace: jenkins-agents
  annotations:
    kubernetes.io/service-account.name: jenkins-agent-manager
type: kubernetes.io/service-account-token
