$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "Kubernetes Lab Lifecycle" -ForegroundColor Cyan
Write-Host "========================"
Write-Host ""
Write-Host "CREATE / PROVISION"
Write-Host "  .\scripts\up.ps1"
Write-Host "  Creates/starts VMs and runs provisioning/platform installation."
Write-Host ""
Write-Host "RUN EXISTING LAB"
Write-Host "  .\scripts\run.ps1"
Write-Host "  Starts existing VMs without provisioning."
Write-Host ""
Write-Host "GRACEFUL DOWN"
Write-Host "  .\scripts\down.ps1"
Write-Host "  Powers off VMs but keeps all VM disks/data/snapshots."
Write-Host ""
Write-Host "SUSPEND"
Write-Host "  .\scripts\suspend.ps1"
Write-Host "  Saves the VM execution state."
Write-Host ""
Write-Host "RESUME"
Write-Host "  .\scripts\resume.ps1"
Write-Host "  Resumes previously suspended VMs."
Write-Host ""
Write-Host "DESTROY"
Write-Host "  .\scripts\destroy.cmd"
Write-Host "  Permanently deletes the lab VMs and local VM state."
Write-Host ""
