apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lab-test-cert
  namespace: cert-manager-test
spec:
  secretName: lab-test-tls
  commonName: lab-cert-manager-test.local
  dnsNames:
    - lab-cert-manager-test.local
  issuerRef:
    name: selfsigned
    kind: Issuer
