apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: velero
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:RELEASE.2025-08-13T08-35-41Z
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set local http://minio.velero.svc:9000 minio minio123; do
                echo "Waiting for MinIO..."
                sleep 3
              done
              mc mb --ignore-existing local/velero
              mc ls local
